on:
  push:
    branches:
      - main

name: deploy-rsconnect

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.1.1'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rsconnect
            RcppArmadillo
            cpp11
            prettyunits
            progress

      - name: Push to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='epiforecasts', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'ecdc_submission')"
