on:
  push:
    branches:
      - main

name: deploy-rsconnect

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Push to shinyapps.io
        with:
          SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
          SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}
        run: |
          rsconnect::setAccountInfo(name = 'hgruson', token = Sys.getenv("SHINYAPPS_TOKEN"), secret = Sys.getenv("SHINYAPPS_SECRET"))
          rsconnect::deployApp()
        shell: Rscript {0}
